version: '3.8'

services:
  php:
    build: ./docker
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tictactoe
    networks:
      - app-network
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: