GET http://localhost:8082/ HTTP/1.1

> {%
    client.test("Request body", function() {
        client.assert(response.body['turn'] === 'X', "Wrong turn response");
    });
%}
###
POST http://localhost:8082/place/x HTTP/1.1
Content-Type: application/json

{
  "x": 1,
  "y": 1
}
> {%
    client.test("Request body", function() {
        console.log(response.body);
        client.assert(response.body['turn'] === 'O', "Wrong turn response");
    });
%}
###
POST http://localhost:8082/place/o HTTP/1.1
Content-Type: application/json

{
  "x": 1,
  "y": 0
}
> {%
    client.test("Request body", function() {
        client.assert(response.body['turn'] === 'X', "Wrong turn response");
    });
%}
###
POST http://localhost:8082/restart HTTP/1.1

> {%
    client.test("Request body", function() {
        client.assert(JSON.stringify(response.body['board']) === '[["","",""],["","",""],["","",""]]', "Game didn't restart");
    });
%}